const EXPS = new Map([
    ['/::)', { file: '100.gif', code: '/::)', title: '微笑',reg:/\/::\)/g }],
    ['/::~', { file: '101.gif', code: '/::~', title: '伤心',reg:/\/::~/g }],
    ['/::B', { file: '102.gif', code: '/::B', title: '美女',reg:/\/::B/g }],
    ['/::|', { file: '103.gif', code: '/::|', title: '发呆',reg:/\/::\|/g }],
    ['/:8-)', { file: '104.gif', code: '/:8-)', title: '墨镜',reg:/\/:8-\)/g }],
    ['/::<', { file: '105.gif', code: '/::<', title: '哭',reg:/\/::</g }],
    ['/::$', { file: '106.gif', code: '/::$', title: '羞',reg:/\/::\$/g }],
    ['/::X', { file: '107.gif', code: '/::X', title: '哑',reg:/\/::X/g }],
    ['/::Z', { file: '108.gif', code: '/::Z', title: '睡',reg:/\/::Z/g }],
    ['/::\'(', { file: '109.gif', code: '/::\'(', title: '哭',reg:/\/::'\(/g }],
    ['/::-|', { file: '110.gif', code: '/::-|', title: '囧',reg:/\/::-\|/g }],
    ['/::@', { file: '111.gif', code: '/::@', title: '怒',reg:/\/::@/g }],
    ['/::P', { file: '112.gif', code: '/::P', title: '调皮',reg:/\/::P/g }],
    ['/::D', { file: '113.gif', code: '/::D', title: '笑',reg:/\/::D/g }],
    ['/::O', { file: '114.gif', code: '/::O', title: '惊讶',reg:/\/::O/g }],
    ['/::(', { file: '115.gif', code: '/::(', title: '难过',reg:/\/::\(/g }],
    ['/::+', { file: '116.gif', code: '/::+', title: '酷',reg:/\/::\+/g }],
    ['/:--b', { file: '117.gif', code: '/:--b', title: '汗',reg:/\/:--b/g }],
    ['/::Q', { file: '118.gif', code: '/::Q', title: '抓狂',reg:/\/::Q/g }],
    ['/::T', { file: '119.gif', code: '/::T', title: '吐',reg:/\/::T/g }],
    ['/:,@P', { file: '120.gif', code: '/:,@P', title: '笑',reg:/\/:,@P/g }],
    ['/:,@-D', { file: '121.gif', code: '/:,@-D', title: '快乐',reg:/\/:,@-D/g }],
    ['/::d', { file: '122.gif', code: '/::d', title: '奇',reg:/\/::d/g }],
    ['/:,@o', { file: '123.gif', code: '/:,@o', title: '傲' ,reg:/\/:,@o/g}],
    ['/::g', { file: '124.gif', code: '/::g', title: '饿',reg:/\/::g/g }],
    ['/:|-)', { file: '125.gif', code: '/:|-)', title: '累' ,reg:/\/:\|-\)/g}],
    ['/::!', { file: '126.gif', code: '/::!', title: '吓',reg:/\/::!/g }],
    ['/::L', { file: '127.gif', code: '/::L', title: '汗', reg:/\/::L/g }],
    ['/::>', { file: '128.gif', code: '/::>', title: '高兴', reg:/\/::>/g }],
    ['/::,@', { file: '129.gif', code: '/::,@', title: '闲', reg:/\/::,@/g }],
    ['/:,@f', { file: '130.gif', code: '/:,@f', title: '努力', reg:/\/:,@f/g}],
    ['/::-S', { file: '131.gif', code: '/::-S', title: '骂', reg:/\/::-S/g }],
    ['/:?', { file: '132.gif', code: '/:?', title: '疑问', reg:/\/:?/g }],
    ['/:,@x', { file: '133.gif', code: '/:,@x', title: '秘密', reg:/\/:,@x/g }],
    ['/:,@@', { file: '134.gif', code: '/:,@@', title: '乱', reg:/\/:,@@/g }],
    ['/::8', { file: '135.gif', code: '/::8', title: '疯', reg:/\/::8/g }],
    ['/:,@!', { file: '136.gif', code: '/:, @!', title: '哀', reg:/\/:,@!/g],
    ['/:!!!', { file: '137.gif', code: '/:!!!', title: '鬼', reg:/\/:!!!/g }],
    ['/:xx', { file: '138.gif', code: '/:xx', title: '打击', reg:/\/:xx/g }],
    ['/:bye', { file: '139.gif', code: '/:bye', title: 'bye', reg:/\/:bye/g }],
    ['/:wipe', { file: '140.gif', code: '/:wipe', title: '汗', reg:/\/:wipe/g }],
    ['/:dig', { file: '141.gif', code: '/:dig', title: '抠', reg:/\/:dig/g }],
    ['/:handclap', { file: '142.gif', code: '/:handclap', title: '鼓掌', reg:/\/:handclap/g }],
    ['/:&-(', { file: '143.gif', code: '/:&-(', title: '糟糕', reg:/\/:\&-\(/g }],
    ['/:B-)', { file: '144.gif', code: '/:B-)', title: '恶搞', reg:/\/:B-)/g }],
    ['/:<@', { file: '145.gif', code: '/:<@', title: '什么', reg:/\/:<@/g }],
    ['/:@>', { file: '146.gif', code: '/:@>', title: '什么', reg:/\/:@>/g }],
    ['/::-O', { file: '147.gif', code: '/::-O', title: '累', reg:/\/::-O/g }],
    ['/:>-|', { file: '148.gif', code: '/:>-|', title: '看', reg:/\/:>-|/g }],
    ['/:P-(', { file: '149.gif', code: '/:P-(', title: '难过', reg:/\/:P-\(/g }],
    ['/::\'|', { file: '150.gif', code: '/::\'|', title: '难过', reg:/\/::\'|/g }],
    ['/:X-)', { file: '151.gif', code: '/:X-)', title: '坏', reg:/\/:X-)/g }],
    ['/::*', { file: '152.gif', code: '/::*', title: '亲', reg:/\/::*/g }],
    ['/:@x', { file: '153.gif', code: '/:@x', title: '吓', reg:/\/:@x/g }],
    ['/:8*', { file: '154.gif', code: '/:8*', title: '可怜', reg:/\/:8*/g }],
    ['/:pd', { file: '155.gif', code: '/:pd', title: '刀', reg:/\/:pd/g }],
    ['/:<W>', { file: '156.gif', code: '/:<W>', title: '水果', reg:/\/:<W>/g }],
    ['/:beer', { file: '157.gif', code: '/:beer', title: '酒', reg:/\/:beer/g }],
    ['/:basketb', { file: '158.gif', code: '/:basketb', title: '篮球', reg:/\/:basketb/g }],
    ['/:oo', { file: '159.gif', code: '/:oo', title: '乒乓', reg:/\/:oo/g }],
    ['/:coffee', { file: '160.gif', code: '/:coffee', title: '咖啡', reg:/\/:coffee/g }],
    ['/:eat', { file: '161.gif', code: '/:eat', title: '美食', reg:/\/:eat/g }],
    ['/:pig', { file: '162.gif', code: '/:pig', title: '动物', reg:/\/:pig/g }],
    ['/:rose', { file: '163.gif', code: '/:rose', title: '鲜花', reg:/\/:rose/g }],
    ['/:fade', { file: '164.gif', code: '/:fade', title: '枯', reg:/\/:fade/g }],
    ['/:showlove', { file: '165.gif', code: '/:showlove', title: '唇', reg:/\/:showlove/g }],
    ['/:heart', { file: '166.gif', code: '/:heart', title: '爱', reg:/\/:heart/g }],
    ['/:break', { file: '167.gif', code: '/:break', title: '分手', reg:/\/:break/g }],
    ['/:cake', { file: '168.gif', code: '/:cake', title: '生日', reg:/\/:cake/g }],
    ['/:li', { file: '169.gif', code: '/:li', title: '电', reg:/\/:li/g }],
    ['/:bome', { file: '170.gif', code: '/:bome', title: '炸弹', reg:/\/:bome/g }],
    ['/:kn', { file: '171.gif', code: '/:kn', title: '刀子', reg:/\/:kn/g }],
    ['/:footb', { file: '172.gif', code: '/:footb', title: '足球', reg:/\/:footb/g }],
    ['/:ladybug', { file: '173.gif', code: '/:ladybug', title: '瓢虫', reg:/\/:ladybug/g }],
    ['/:shit', { file: '174.gif', code: '/:shit', title: '翔', reg:/\/:shit/g }],
    ['/:moon', { file: '175.gif', code: '/:moon', title: '月亮', reg:/\/:moon/g }],
    ['/:sun', { file: '176.gif', code: '/:sun', title: '太阳', reg:/\/:sun/g }],
    ['/:gift', { file: '177.gif', code: '/:gift', title: '礼物', reg:/\/:gift/g }],
    ['/:hug', { file: '178.gif', code: '/:hug', title: '抱抱', reg:/\/:hug/g }],
    ['/:strong', { file: '179.gif', code: '/:strong', title: '拇指', reg:/\/:strong/g }],
    ['/:weak', { file: '180.gif', code: '/:weak', title: '贬低', reg:/\/:weak/g }],
    ['/:share', { file: '181.gif', code: '/:share', title: '握手', reg:/\/:share/g }],
    ['/:v', { file: '182.gif', code: '/:v', title: '剪刀手', reg:/\/:v/g }],
    ['/:@)', { file: '183.gif', code: '/:@)', title: '抱拳', reg:/\/:@)/g }],
    ['/:jj', { file: '184.gif', code: '/:jj', title: '勾引', reg:/\/:jj/g }],
    ['/:@@', { file: '185.gif', code: '/:@@', title: '拳头', reg:/\/:@@/g }],
    ['/:bad', { file: '186.gif', code: '/:bad', title: '小拇指', reg:/\/:bad/g }],
    ['/:lvu', { file: '187.gif', code: '/:lvu', title: '拇指八', reg:/\/:lvu/g }],
    ['/:no', { file: '188.gif', code: '/:no', title: '食指', reg:/\/:no/g }],
    ['/:ok', { file: '189.gif', code: '/:ok', title: 'ok', reg:/\/:ok/g }],
    ['/:love', { file: '190.gif', code: '/:love', title: '情侣', reg:/\/:love/g }],
    ['/:<L>', { file: '191.gif', code: '/:<L>', title: '爱心', reg:/\/:<L>/g }],
    ['/:jump', { file: '192.gif', code: '/:jump', title: '蹦哒', reg:/\/:jump/g }],
    ['/:shake', { file: '193.gif', code: '/:shake', title: '颤抖', reg:/\/:shake/g }],
    ['/:<O>', { file: '194.gif', code: '/:<O>', title: '怄气', reg:/\/:<O>/g }],
    ['/:circle', { file: '195.gif', code: '/:circle', title: '跳舞', reg:/\/:circle/g }],
    ['/:kotow', { file: '196.gif', code: '/:kotow', title: '发呆', reg:/\/:kotow/g }],
    ['/:turn', { file: '197.gif', code: '/:turn', title: '背着', reg:/\/:turn/g }],
    ['/:skip', { file: '198.gif', code: '/:skip', title: '伸手', reg:/\/:skip/g }],
    ['/:oY', { file: '199.gif', code: '/:oY', title: '耍帅', reg:/\/:oY/g }]

])